name = "MultivariateStats"
uuid = "9a4da972-b025-11e8-0eaa-35352734416b"
keywords = ["multivariate statistics", "dimensionality reduction"]
license = "MIT"
desc = "A Julia package for multivariate statistics and data analysis"
repository = "https://github.com/JuliaStats/MultivariateStats.jl.git"
version = "0.6.0"

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
